spring:
  application:
    name: dream-shop

  server:
    port: 8081

  datasource:
    url: jdbc:mysql://localhost:3306/shopping_cart?serverTimezone=UTC
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQLDialect

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  logging:
   level:
    org:
     springframework: DEBUG